version: '3'

services:
  nginx-ephir:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
      - ./_docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./_docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network-ephir

  php-fpm-ephir:
    build:
      context: ./_docker-compose/php-fpm/
      dockerfile: Dockerfile
    image: php-fpm-ephir-im
    volumes:
      - .:/var/www
      - ./_docker-compose/zsh/-.zshrc:/home/www/.zshrc
      - ./_docker-compose/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network-ephir

networks:
  app-network-ephir:
    driver: bridge
